// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package view

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ReportsPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"grid gap-6\"><div><h1 class=\"text-2xl font-semibold\">Relatorios</h1><p class=\"mt-1 text-sm text-slate-300\">Receita, inadimplencia e status de alunos em um so lugar.</p></div><div class=\"grid gap-4 md:grid-cols-3\"><div class=\"rounded-2xl border border-slate-800 bg-slate-900/60 p-6\"><p class=\"text-sm text-slate-400\">Receita mensal</p><p class=\"mt-2 text-3xl font-semibold text-emerald-200\">R$ 38.500</p><p class=\"mt-1 text-xs text-slate-500\">ultimos 30 dias</p></div><div class=\"rounded-2xl border border-slate-800 bg-slate-900/60 p-6\"><p class=\"text-sm text-slate-400\">Alunos ativos</p><p class=\"mt-2 text-3xl font-semibold text-sky-200\">81%</p><p class=\"mt-1 text-xs text-slate-500\">ativo vs inativo</p></div><div class=\"rounded-2xl border border-slate-800 bg-slate-900/60 p-6\"><p class=\"text-sm text-slate-400\">Inadimplencia</p><p class=\"mt-2 text-3xl font-semibold text-rose-200\">12%</p><p class=\"mt-1 text-xs text-slate-500\">base total</p></div></div><div class=\"rounded-2xl border border-slate-800 bg-slate-900/60 p-6\"><p class=\"text-sm text-slate-300\">Filtros principais</p><div class=\"mt-3 grid gap-2 text-sm text-slate-400\"><p>Periodo: diario / semanal / mensal</p><p>Proximos vencimentos: 7 / 15 / 30 dias</p><p>Status do aluno: ativo, inativo, suspenso</p></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
