// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: billing_periods.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBillingPeriod = `-- name: CreateBillingPeriod :one
INSERT INTO billing_periods (
  subscription_id,
  period_start,
  period_end,
  amount_due_cents,
  amount_paid_cents,
  status
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, subscription_id, period_start, period_end, amount_due_cents, amount_paid_cents, status, created_at, updated_at
`

type CreateBillingPeriodParams struct {
	SubscriptionID  pgtype.UUID         `json:"subscription_id"`
	PeriodStart     pgtype.Date         `json:"period_start"`
	PeriodEnd       pgtype.Date         `json:"period_end"`
	AmountDueCents  int64               `json:"amount_due_cents"`
	AmountPaidCents int64               `json:"amount_paid_cents"`
	Status          BillingPeriodStatus `json:"status"`
}

func (q *Queries) CreateBillingPeriod(ctx context.Context, arg CreateBillingPeriodParams) (BillingPeriod, error) {
	row := q.db.QueryRow(ctx, createBillingPeriod,
		arg.SubscriptionID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.AmountDueCents,
		arg.AmountPaidCents,
		arg.Status,
	)
	var i BillingPeriod
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.AmountDueCents,
		&i.AmountPaidCents,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBillingPeriodsBySubscription = `-- name: ListBillingPeriodsBySubscription :many
SELECT id, subscription_id, period_start, period_end, amount_due_cents, amount_paid_cents, status, created_at, updated_at FROM billing_periods WHERE subscription_id = $1 ORDER BY period_start
`

func (q *Queries) ListBillingPeriodsBySubscription(ctx context.Context, subscriptionID pgtype.UUID) ([]BillingPeriod, error) {
	rows, err := q.db.Query(ctx, listBillingPeriodsBySubscription, subscriptionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BillingPeriod
	for rows.Next() {
		var i BillingPeriod
		if err := rows.Scan(
			&i.ID,
			&i.SubscriptionID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.AmountDueCents,
			&i.AmountPaidCents,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenBillingPeriodsBySubscription = `-- name: ListOpenBillingPeriodsBySubscription :many
SELECT id, subscription_id, period_start, period_end, amount_due_cents, amount_paid_cents, status, created_at, updated_at
FROM billing_periods
WHERE subscription_id = $1
  AND status IN ('open', 'partial', 'overdue')
ORDER BY period_end
`

func (q *Queries) ListOpenBillingPeriodsBySubscription(ctx context.Context, subscriptionID pgtype.UUID) ([]BillingPeriod, error) {
	rows, err := q.db.Query(ctx, listOpenBillingPeriodsBySubscription, subscriptionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BillingPeriod
	for rows.Next() {
		var i BillingPeriod
		if err := rows.Scan(
			&i.ID,
			&i.SubscriptionID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.AmountDueCents,
			&i.AmountPaidCents,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBillingPeriodsOverdue = `-- name: MarkBillingPeriodsOverdue :exec
UPDATE billing_periods
SET status = 'overdue',
    updated_at = now()
WHERE subscription_id = $1
  AND status IN ('open', 'partial')
  AND period_end < $2
`

type MarkBillingPeriodsOverdueParams struct {
	SubscriptionID pgtype.UUID `json:"subscription_id"`
	PeriodEnd      pgtype.Date `json:"period_end"`
}

func (q *Queries) MarkBillingPeriodsOverdue(ctx context.Context, arg MarkBillingPeriodsOverdueParams) error {
	_, err := q.db.Exec(ctx, markBillingPeriodsOverdue, arg.SubscriptionID, arg.PeriodEnd)
	return err
}

const updateBillingPeriod = `-- name: UpdateBillingPeriod :one
UPDATE billing_periods
SET
  amount_paid_cents = $2,
  status = $3,
  updated_at = now()
WHERE id = $1
RETURNING id, subscription_id, period_start, period_end, amount_due_cents, amount_paid_cents, status, created_at, updated_at
`

type UpdateBillingPeriodParams struct {
	ID              pgtype.UUID         `json:"id"`
	AmountPaidCents int64               `json:"amount_paid_cents"`
	Status          BillingPeriodStatus `json:"status"`
}

func (q *Queries) UpdateBillingPeriod(ctx context.Context, arg UpdateBillingPeriodParams) (BillingPeriod, error) {
	row := q.db.QueryRow(ctx, updateBillingPeriod, arg.ID, arg.AmountPaidCents, arg.Status)
	var i BillingPeriod
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.AmountDueCents,
		&i.AmountPaidCents,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
