// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BillingPeriod struct {
	ID              pgtype.UUID        `json:"id"`
	SubscriptionID  pgtype.UUID        `json:"subscription_id"`
	PeriodStart     pgtype.Date        `json:"period_start"`
	PeriodEnd       pgtype.Date        `json:"period_end"`
	AmountDueCents  int64              `json:"amount_due_cents"`
	AmountPaidCents int64              `json:"amount_paid_cents"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Payment struct {
	ID             pgtype.UUID        `json:"id"`
	SubscriptionID pgtype.UUID        `json:"subscription_id"`
	PaidAt         pgtype.Timestamptz `json:"paid_at"`
	AmountCents    int64              `json:"amount_cents"`
	Method         string             `json:"method"`
	Reference      pgtype.Text        `json:"reference"`
	Notes          pgtype.Text        `json:"notes"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Kind           string             `json:"kind"`
	CreditCents    int64              `json:"credit_cents"`
}

type PaymentAllocation struct {
	PaymentID       pgtype.UUID        `json:"payment_id"`
	BillingPeriodID pgtype.UUID        `json:"billing_period_id"`
	AmountCents     int64              `json:"amount_cents"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Plan struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	DurationDays int32              `json:"duration_days"`
	PriceCents   int64              `json:"price_cents"`
	Active       bool               `json:"active"`
	Description  pgtype.Text        `json:"description"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Student struct {
	ID        pgtype.UUID        `json:"id"`
	FullName  string             `json:"full_name"`
	BirthDate pgtype.Date        `json:"birth_date"`
	Gender    pgtype.Text        `json:"gender"`
	Phone     pgtype.Text        `json:"phone"`
	Email     pgtype.Text        `json:"email"`
	Cpf       pgtype.Text        `json:"cpf"`
	Address   pgtype.Text        `json:"address"`
	Notes     pgtype.Text        `json:"notes"`
	PhotoUrl  pgtype.Text        `json:"photo_url"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Subscription struct {
	ID         pgtype.UUID        `json:"id"`
	StudentID  pgtype.UUID        `json:"student_id"`
	PlanID     pgtype.UUID        `json:"plan_id"`
	StartDate  pgtype.Date        `json:"start_date"`
	EndDate    pgtype.Date        `json:"end_date"`
	Status     string             `json:"status"`
	PriceCents int64              `json:"price_cents"`
	PaymentDay int32              `json:"payment_day"`
	AutoRenew  bool               `json:"auto_renew"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type SubscriptionBalance struct {
	SubscriptionID pgtype.UUID        `json:"subscription_id"`
	CreditCents    int64              `json:"credit_cents"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	Active       bool               `json:"active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
