// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
  subscription_id,
  paid_at,
  amount_cents,
  method,
  reference,
  notes,
  status,
  kind,
  credit_cents,
  idempotency_key
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, subscription_id, paid_at, amount_cents, method, reference, notes, status, created_at, kind, credit_cents, idempotency_key
`

type CreatePaymentParams struct {
	SubscriptionID pgtype.UUID        `json:"subscription_id"`
	PaidAt         pgtype.Timestamptz `json:"paid_at"`
	AmountCents    int64              `json:"amount_cents"`
	Method         string             `json:"method"`
	Reference      pgtype.Text        `json:"reference"`
	Notes          pgtype.Text        `json:"notes"`
	Status         string             `json:"status"`
	Kind           string             `json:"kind"`
	CreditCents    int64              `json:"credit_cents"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.SubscriptionID,
		arg.PaidAt,
		arg.AmountCents,
		arg.Method,
		arg.Reference,
		arg.Notes,
		arg.Status,
		arg.Kind,
		arg.CreditCents,
		arg.IdempotencyKey,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.PaidAt,
		&i.AmountCents,
		&i.Method,
		&i.Reference,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.Kind,
		&i.CreditCents,
		&i.IdempotencyKey,
	)
	return i, err
}

const getPayment = `-- name: GetPayment :one
SELECT id, subscription_id, paid_at, amount_cents, method, reference, notes, status, created_at, kind, credit_cents, idempotency_key FROM payments WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPayment(ctx context.Context, id pgtype.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.PaidAt,
		&i.AmountCents,
		&i.Method,
		&i.Reference,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.Kind,
		&i.CreditCents,
		&i.IdempotencyKey,
	)
	return i, err
}

const getPaymentByIdempotencyKey = `-- name: GetPaymentByIdempotencyKey :one
SELECT id, subscription_id, paid_at, amount_cents, method, reference, notes, status, created_at, kind, credit_cents, idempotency_key FROM payments WHERE idempotency_key = $1 LIMIT 1
`

func (q *Queries) GetPaymentByIdempotencyKey(ctx context.Context, idempotencyKey pgtype.Text) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByIdempotencyKey, idempotencyKey)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.PaidAt,
		&i.AmountCents,
		&i.Method,
		&i.Reference,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.Kind,
		&i.CreditCents,
		&i.IdempotencyKey,
	)
	return i, err
}

const listPaymentsByPeriod = `-- name: ListPaymentsByPeriod :many
SELECT id, subscription_id, paid_at, amount_cents, method, reference, notes, status, created_at, kind, credit_cents, idempotency_key
FROM payments
WHERE paid_at >= $1 AND paid_at < $2
ORDER BY paid_at DESC
`

type ListPaymentsByPeriodParams struct {
	PaidAt   pgtype.Timestamptz `json:"paid_at"`
	PaidAt_2 pgtype.Timestamptz `json:"paid_at_2"`
}

func (q *Queries) ListPaymentsByPeriod(ctx context.Context, arg ListPaymentsByPeriodParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByPeriod, arg.PaidAt, arg.PaidAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.SubscriptionID,
			&i.PaidAt,
			&i.AmountCents,
			&i.Method,
			&i.Reference,
			&i.Notes,
			&i.Status,
			&i.CreatedAt,
			&i.Kind,
			&i.CreditCents,
			&i.IdempotencyKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsBySubscription = `-- name: ListPaymentsBySubscription :many
SELECT id, subscription_id, paid_at, amount_cents, method, reference, notes, status, created_at, kind, credit_cents, idempotency_key FROM payments WHERE subscription_id = $1 ORDER BY paid_at DESC
`

func (q *Queries) ListPaymentsBySubscription(ctx context.Context, subscriptionID pgtype.UUID) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsBySubscription, subscriptionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.SubscriptionID,
			&i.PaidAt,
			&i.AmountCents,
			&i.Method,
			&i.Reference,
			&i.Notes,
			&i.Status,
			&i.CreatedAt,
			&i.Kind,
			&i.CreditCents,
			&i.IdempotencyKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePayment = `-- name: UpdatePayment :one
UPDATE payments
SET
  subscription_id = $2,
  paid_at = $3,
  amount_cents = $4,
  method = $5,
  reference = $6,
  notes = $7,
  status = $8,
  kind = $9,
  credit_cents = $10
WHERE id = $1
RETURNING id, subscription_id, paid_at, amount_cents, method, reference, notes, status, created_at, kind, credit_cents, idempotency_key
`

type UpdatePaymentParams struct {
	ID             pgtype.UUID        `json:"id"`
	SubscriptionID pgtype.UUID        `json:"subscription_id"`
	PaidAt         pgtype.Timestamptz `json:"paid_at"`
	AmountCents    int64              `json:"amount_cents"`
	Method         string             `json:"method"`
	Reference      pgtype.Text        `json:"reference"`
	Notes          pgtype.Text        `json:"notes"`
	Status         string             `json:"status"`
	Kind           string             `json:"kind"`
	CreditCents    int64              `json:"credit_cents"`
}

func (q *Queries) UpdatePayment(ctx context.Context, arg UpdatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePayment,
		arg.ID,
		arg.SubscriptionID,
		arg.PaidAt,
		arg.AmountCents,
		arg.Method,
		arg.Reference,
		arg.Notes,
		arg.Status,
		arg.Kind,
		arg.CreditCents,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.PaidAt,
		&i.AmountCents,
		&i.Method,
		&i.Reference,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.Kind,
		&i.CreditCents,
		&i.IdempotencyKey,
	)
	return i, err
}
