// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plans.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlan = `-- name: CreatePlan :one
INSERT INTO plans (
  name,
  duration_days,
  price_cents,
  active,
  description
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, name, duration_days, price_cents, active, description, created_at, updated_at
`

type CreatePlanParams struct {
	Name         string      `json:"name"`
	DurationDays int32       `json:"duration_days"`
	PriceCents   int64       `json:"price_cents"`
	Active       bool        `json:"active"`
	Description  pgtype.Text `json:"description"`
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, createPlan,
		arg.Name,
		arg.DurationDays,
		arg.PriceCents,
		arg.Active,
		arg.Description,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DurationDays,
		&i.PriceCents,
		&i.Active,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlan = `-- name: GetPlan :one
SELECT id, name, duration_days, price_cents, active, description, created_at, updated_at FROM plans WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPlan(ctx context.Context, id pgtype.UUID) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlan, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DurationDays,
		&i.PriceCents,
		&i.Active,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActivePlans = `-- name: ListActivePlans :many
SELECT id, name, duration_days, price_cents, active, description, created_at, updated_at FROM plans WHERE active = true ORDER BY name
`

func (q *Queries) ListActivePlans(ctx context.Context) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listActivePlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DurationDays,
			&i.PriceCents,
			&i.Active,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlan = `-- name: UpdatePlan :one
UPDATE plans
SET
  name = $2,
  duration_days = $3,
  price_cents = $4,
  active = $5,
  description = $6,
  updated_at = now()
WHERE id = $1
RETURNING id, name, duration_days, price_cents, active, description, created_at, updated_at
`

type UpdatePlanParams struct {
	ID           pgtype.UUID `json:"id"`
	Name         string      `json:"name"`
	DurationDays int32       `json:"duration_days"`
	PriceCents   int64       `json:"price_cents"`
	Active       bool        `json:"active"`
	Description  pgtype.Text `json:"description"`
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, updatePlan,
		arg.ID,
		arg.Name,
		arg.DurationDays,
		arg.PriceCents,
		arg.Active,
		arg.Description,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DurationDays,
		&i.PriceCents,
		&i.Active,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
