// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error)
	CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DelinquentSubscriptions(ctx context.Context, dollar_1 pgtype.Date) ([]DelinquentSubscriptionsRow, error)
	GetPlan(ctx context.Context, id pgtype.UUID) (Plan, error)
	GetStudent(ctx context.Context, id pgtype.UUID) (Student, error)
	GetSubscription(ctx context.Context, id pgtype.UUID) (Subscription, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListActivePlans(ctx context.Context) ([]Plan, error)
	ListPaymentsByPeriod(ctx context.Context, arg ListPaymentsByPeriodParams) ([]Payment, error)
	ListPaymentsBySubscription(ctx context.Context, subscriptionID pgtype.UUID) ([]Payment, error)
	ListSubscriptionsByStudent(ctx context.Context, studentID pgtype.UUID) ([]Subscription, error)
	ListSubscriptionsDueBetween(ctx context.Context, arg ListSubscriptionsDueBetweenParams) ([]Subscription, error)
	RevenueByPeriod(ctx context.Context, arg RevenueByPeriodParams) (RevenueByPeriodRow, error)
	SearchStudents(ctx context.Context, arg SearchStudentsParams) ([]Student, error)
	StudentsByStatus(ctx context.Context) ([]StudentsByStatusRow, error)
	UpcomingDue(ctx context.Context, arg UpcomingDueParams) ([]UpcomingDueRow, error)
	UpdatePlan(ctx context.Context, arg UpdatePlanParams) (Plan, error)
	UpdateStudent(ctx context.Context, arg UpdateStudentParams) (Student, error)
	UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) (Subscription, error)
}

var _ Querier = (*Queries)(nil)
