// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: students.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStudent = `-- name: CreateStudent :one
INSERT INTO students (
  full_name,
  birth_date,
  gender,
  phone,
  email,
  cpf,
  address,
  notes,
  photo_url,
  status
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, full_name, birth_date, gender, phone, email, cpf, address, notes, photo_url, status, created_at, updated_at
`

type CreateStudentParams struct {
	FullName  string        `json:"full_name"`
	BirthDate pgtype.Date   `json:"birth_date"`
	Gender    pgtype.Text   `json:"gender"`
	Phone     pgtype.Text   `json:"phone"`
	Email     pgtype.Text   `json:"email"`
	Cpf       pgtype.Text   `json:"cpf"`
	Address   pgtype.Text   `json:"address"`
	Notes     pgtype.Text   `json:"notes"`
	PhotoUrl  pgtype.Text   `json:"photo_url"`
	Status    StudentStatus `json:"status"`
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, createStudent,
		arg.FullName,
		arg.BirthDate,
		arg.Gender,
		arg.Phone,
		arg.Email,
		arg.Cpf,
		arg.Address,
		arg.Notes,
		arg.PhotoUrl,
		arg.Status,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.BirthDate,
		&i.Gender,
		&i.Phone,
		&i.Email,
		&i.Cpf,
		&i.Address,
		&i.Notes,
		&i.PhotoUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStudent = `-- name: GetStudent :one
SELECT id, full_name, birth_date, gender, phone, email, cpf, address, notes, photo_url, status, created_at, updated_at FROM students WHERE id = $1 LIMIT 1
`

func (q *Queries) GetStudent(ctx context.Context, id pgtype.UUID) (Student, error) {
	row := q.db.QueryRow(ctx, getStudent, id)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.BirthDate,
		&i.Gender,
		&i.Phone,
		&i.Email,
		&i.Cpf,
		&i.Address,
		&i.Notes,
		&i.PhotoUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchStudents = `-- name: SearchStudents :many
SELECT id, full_name, birth_date, gender, phone, email, cpf, address, notes, photo_url, status, created_at, updated_at
FROM students
WHERE ($1 = '' OR full_name ILIKE '%' || $1 || '%' OR phone ILIKE '%' || $1 || '%' OR cpf ILIKE '%' || $1 || '%')
  AND (COALESCE(array_length($2::student_status[], 1), 0) = 0 OR status = ANY($2::student_status[]))
ORDER BY full_name
LIMIT $3 OFFSET $4
`

type SearchStudentsParams struct {
	Column1 interface{}     `json:"column_1"`
	Column2 []StudentStatus `json:"column_2"`
	Limit   int32           `json:"limit"`
	Offset  int32           `json:"offset"`
}

func (q *Queries) SearchStudents(ctx context.Context, arg SearchStudentsParams) ([]Student, error) {
	rows, err := q.db.Query(ctx, searchStudents,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Student
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.BirthDate,
			&i.Gender,
			&i.Phone,
			&i.Email,
			&i.Cpf,
			&i.Address,
			&i.Notes,
			&i.PhotoUrl,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStudent = `-- name: UpdateStudent :one
UPDATE students
SET
  full_name = $2,
  birth_date = $3,
  gender = $4,
  phone = $5,
  email = $6,
  cpf = $7,
  address = $8,
  notes = $9,
  photo_url = $10,
  status = $11,
  updated_at = now()
WHERE id = $1
RETURNING id, full_name, birth_date, gender, phone, email, cpf, address, notes, photo_url, status, created_at, updated_at
`

type UpdateStudentParams struct {
	ID        pgtype.UUID   `json:"id"`
	FullName  string        `json:"full_name"`
	BirthDate pgtype.Date   `json:"birth_date"`
	Gender    pgtype.Text   `json:"gender"`
	Phone     pgtype.Text   `json:"phone"`
	Email     pgtype.Text   `json:"email"`
	Cpf       pgtype.Text   `json:"cpf"`
	Address   pgtype.Text   `json:"address"`
	Notes     pgtype.Text   `json:"notes"`
	PhotoUrl  pgtype.Text   `json:"photo_url"`
	Status    StudentStatus `json:"status"`
}

func (q *Queries) UpdateStudent(ctx context.Context, arg UpdateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, updateStudent,
		arg.ID,
		arg.FullName,
		arg.BirthDate,
		arg.Gender,
		arg.Phone,
		arg.Email,
		arg.Cpf,
		arg.Address,
		arg.Notes,
		arg.PhotoUrl,
		arg.Status,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.BirthDate,
		&i.Gender,
		&i.Phone,
		&i.Email,
		&i.Cpf,
		&i.Address,
		&i.Notes,
		&i.PhotoUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
