// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (
  student_id,
  plan_id,
  start_date,
  end_date,
  status,
  price_cents,
  payment_day,
  auto_renew
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, student_id, plan_id, start_date, end_date, status, price_cents, payment_day, auto_renew, created_at, updated_at
`

type CreateSubscriptionParams struct {
	StudentID  pgtype.UUID `json:"student_id"`
	PlanID     pgtype.UUID `json:"plan_id"`
	StartDate  pgtype.Date `json:"start_date"`
	EndDate    pgtype.Date `json:"end_date"`
	Status     string      `json:"status"`
	PriceCents int64       `json:"price_cents"`
	PaymentDay int32       `json:"payment_day"`
	AutoRenew  bool        `json:"auto_renew"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.StudentID,
		arg.PlanID,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
		arg.PriceCents,
		arg.PaymentDay,
		arg.AutoRenew,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.PlanID,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.PriceCents,
		&i.PaymentDay,
		&i.AutoRenew,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscription = `-- name: GetSubscription :one
SELECT id, student_id, plan_id, start_date, end_date, status, price_cents, payment_day, auto_renew, created_at, updated_at FROM subscriptions WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSubscription(ctx context.Context, id pgtype.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscription, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.PlanID,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.PriceCents,
		&i.PaymentDay,
		&i.AutoRenew,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSubscriptionsByStudent = `-- name: ListSubscriptionsByStudent :many
SELECT id, student_id, plan_id, start_date, end_date, status, price_cents, payment_day, auto_renew, created_at, updated_at FROM subscriptions WHERE student_id = $1 ORDER BY start_date DESC
`

func (q *Queries) ListSubscriptionsByStudent(ctx context.Context, studentID pgtype.UUID) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsByStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.PlanID,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.PriceCents,
			&i.PaymentDay,
			&i.AutoRenew,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsDueBetween = `-- name: ListSubscriptionsDueBetween :many
SELECT id, student_id, plan_id, start_date, end_date, status, price_cents, payment_day, auto_renew, created_at, updated_at
FROM subscriptions
WHERE status = 'active'
  AND end_date BETWEEN $1 AND $2
ORDER BY end_date
`

type ListSubscriptionsDueBetweenParams struct {
	EndDate   pgtype.Date `json:"end_date"`
	EndDate_2 pgtype.Date `json:"end_date_2"`
}

func (q *Queries) ListSubscriptionsDueBetween(ctx context.Context, arg ListSubscriptionsDueBetweenParams) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsDueBetween, arg.EndDate, arg.EndDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.PlanID,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.PriceCents,
			&i.PaymentDay,
			&i.AutoRenew,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubscription = `-- name: UpdateSubscription :one
UPDATE subscriptions
SET
  start_date = $2,
  end_date = $3,
  status = $4,
  price_cents = $5,
  payment_day = $6,
  auto_renew = $7,
  updated_at = now()
WHERE id = $1
RETURNING id, student_id, plan_id, start_date, end_date, status, price_cents, payment_day, auto_renew, created_at, updated_at
`

type UpdateSubscriptionParams struct {
	ID         pgtype.UUID `json:"id"`
	StartDate  pgtype.Date `json:"start_date"`
	EndDate    pgtype.Date `json:"end_date"`
	Status     string      `json:"status"`
	PriceCents int64       `json:"price_cents"`
	PaymentDay int32       `json:"payment_day"`
	AutoRenew  bool        `json:"auto_renew"`
}

func (q *Queries) UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, updateSubscription,
		arg.ID,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
		arg.PriceCents,
		arg.PaymentDay,
		arg.AutoRenew,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.PlanID,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.PriceCents,
		&i.PaymentDay,
		&i.AutoRenew,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAutoRenewSubscriptions = `-- name: ListAutoRenewSubscriptions :many
SELECT id, student_id, plan_id, start_date, end_date, status, price_cents, payment_day, auto_renew, created_at, updated_at
FROM subscriptions
WHERE status = 'active'
  AND auto_renew = true
ORDER BY start_date
`

func (q *Queries) ListAutoRenewSubscriptions(ctx context.Context) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listAutoRenewSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.PlanID,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.PriceCents,
			&i.PaymentDay,
			&i.AutoRenew,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
