// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package view

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func HomePage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"grid gap-6\"><div class=\"rounded-2xl border border-emerald-400/20 bg-slate-900/70 p-8 shadow-xl shadow-emerald-500/10\"><p class=\"text-xs uppercase tracking-[0.35em] text-emerald-300\">Resumo</p><h1 class=\"mt-3 text-3xl font-semibold\">Tudo que voce precisa para manter alunos ativos e financas em dia.</h1><p class=\"mt-2 text-sm text-slate-300\">Acompanhe matriculas, assinaturas e pagamentos com visoes rapidas para a operacao diaria.</p><div class=\"mt-6 flex flex-wrap gap-3 text-sm\"><a class=\"rounded-full bg-emerald-400/15 px-4 py-2 text-emerald-200 hover:bg-emerald-400/25\" href=\"/students\">Cadastrar aluno</a> <a class=\"rounded-full border border-slate-700 px-4 py-2 text-slate-200 hover:border-emerald-400/40\" href=\"/subscriptions\">Vincular plano</a> <a class=\"rounded-full border border-slate-700 px-4 py-2 text-slate-200 hover:border-emerald-400/40\" href=\"/payments\">Registrar pagamento</a></div></div><div class=\"grid gap-4 md:grid-cols-3\"><div class=\"rounded-2xl border border-slate-800 bg-slate-900/60 p-6\"><p class=\"text-sm text-slate-400\">Alunos ativos</p><p class=\"mt-2 text-3xl font-semibold text-emerald-200\">128</p><p class=\"mt-1 text-xs text-slate-500\">+6 no mes atual</p></div><div class=\"rounded-2xl border border-slate-800 bg-slate-900/60 p-6\"><p class=\"text-sm text-slate-400\">Inadimplentes</p><p class=\"mt-2 text-3xl font-semibold text-amber-200\">14</p><p class=\"mt-1 text-xs text-slate-500\">ultimos 7 dias</p></div><div class=\"rounded-2xl border border-slate-800 bg-slate-900/60 p-6\"><p class=\"text-sm text-slate-400\">Receita prevista</p><p class=\"mt-2 text-3xl font-semibold text-sky-200\">R$ 42.800</p><p class=\"mt-1 text-xs text-slate-500\">mes corrente</p></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
