// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package view

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func PaymentsPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"grid gap-6\"><div><h1 class=\"text-2xl font-semibold\">Pagamentos</h1><p class=\"mt-1 text-sm text-slate-300\">Registre pagamentos manuais e acompanhe comprovantes.</p></div><div class=\"rounded-2xl border border-slate-800 bg-slate-900/60 p-6\"><div class=\"grid gap-4 md:grid-cols-2\"><div class=\"rounded-xl border border-slate-800 bg-slate-950/60 p-4\"><p class=\"text-sm text-slate-400\">Ultimos recebimentos</p><ul class=\"mt-3 grid gap-2 text-sm text-slate-300\"><li>Pix - R$ 220 - Hoje 09:40</li><li>Dinheiro - R$ 180 - Ontem 18:10</li><li>Cartao - R$ 420 - 2 dias</li></ul></div><div class=\"rounded-xl border border-slate-800 bg-slate-950/60 p-4\"><p class=\"text-sm text-slate-400\">Registrar novo</p><div class=\"mt-3 grid gap-2 text-sm text-slate-300\"><p>Aluno + assinatura</p><p>Metodo - valor - referencia</p><p>Observacoes e comprovante</p></div></div></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
