// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package view

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func SubscriptionsPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"grid gap-6\"><div><h1 class=\"text-2xl font-semibold\">Assinaturas</h1><p class=\"mt-1 text-sm text-slate-300\">Vincule planos aos alunos e acompanhe os vencimentos.</p></div><div class=\"grid gap-4 md:grid-cols-2\"><div class=\"rounded-2xl border border-slate-800 bg-slate-900/60 p-6\"><p class=\"text-sm text-slate-400\">Renovacoes proximas</p><p class=\"mt-2 text-3xl font-semibold text-amber-200\">9</p><p class=\"mt-1 text-xs text-slate-500\">proximos 15 dias</p></div><div class=\"rounded-2xl border border-slate-800 bg-slate-900/60 p-6\"><p class=\"text-sm text-slate-400\">Suspensas</p><p class=\"mt-2 text-3xl font-semibold text-rose-200\">3</p><p class=\"mt-1 text-xs text-slate-500\">pausas em andamento</p></div></div><div class=\"rounded-2xl border border-slate-800 bg-slate-900/60 p-6\"><p class=\"text-sm text-slate-300\">Fluxo principal</p><ol class=\"mt-3 grid gap-2 text-sm text-slate-400\"><li>1. Selecionar aluno e plano</li><li>2. Ajustar preco negociado e data de inicio</li><li>3. Confirmar vencimento e status inicial</li></ol></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
